-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
        name: mypy-main
        files: ^webauthn_rp/
        pass_filenames: false
        args: [--no-strict-optional, --ignore-missing-imports, webauthn_rp]
    -   id: mypy
        name: mypy-tests
        files: ^tests/
        pass_filenames: false
        args: [--no-strict-optional, --ignore-missing-imports, tests]
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    -   id: yapf
        args: [--recursive, --quiet, webauthn_rp, tests, examples]
-   repo: https://github.com/timothycrosley/isort
    rev: "5.0.3"
    hooks:
    -   id: isort
        args: [--check, --ignore-whitespace, webauthn_rp, tests, examples]