language: python
python:
  - "3.6"
install:
  - pip install .[test]
script:
  - mypy --ignore-missing-imports webauthn_rp
  - pytest
  - yapf --recursive webauthn_rp --diff
  - yapf --recursive tests --diff
  - yapf setup.py --diff