language: python
python:
  - "3.6.2"
  - "3.7"
  - "3.8"
install:
  - pip install .
  - pip install pytest==5.4 pytest-cov==2.7 mypy==0.782 yapf==0.30 codecov==2.0
script:
  - mypy --ignore-missing-imports webauthn_rp
  - pytest --cov=webauthn_rp
  - yapf --recursive webauthn_rp --diff
  - yapf --recursive tests --diff
  - yapf --recursive examples --diff
  - codecov
